services:

# We want to run the database first, that way we can see the output of the app last. 
  db:
    image: mysql:8.0
    container_name: notification-db
    environment:
      MYSQL_DATABASE: message_data
      MYSQL_USER: dev
      MYSQL_PASSWORD: ops
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
  app:
    container_name: notification-app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/data
    restart: unless-stopped
    depends_on:
      - db

volumes:
  mysql_data:
