services:
  app:
    container_name: notification-app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/data
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: notification-db
    environment:
      MYSQL_DATABASE: message_data
      MYSQL_USER: dev
      MYSQL_PASSWORD: ops
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
